/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Returns the version of the linked native addon. */
export declare function version(): string
/** Configuration options for instantiating a codec. */
export interface JsCodecConfig {
  /** Audio sample rate in Hz (e.g. 48000). */
  sampleRate?: number
  /** Number of channels (e.g. 2 for stereo). */
  channels?: number
  /** Sample format string: "s16", "s32", "f32", "f64", "s16p", "f32p". */
  sampleFormat?: string
  /** Bitrate hint for encoders (bits/sec). */
  bitrate?: number
  /** Codec-specific extra data. */
  extraData?: Buffer
}
/** Static description of a codec. */
export interface JsCodecDescriptor {
  /** Short stable id (`"pcm_s16le"`, `"opus"`). */
  name: string
  /** Long human-readable name. */
  longName: string
  /** "audio" / "video" / "subtitle". */
  kind: string
  /** Whether this codec can decode. */
  canDecode: boolean
  /** Whether this codec can encode. */
  canEncode: boolean
  /** Whether decoding is bit-exact. */
  isLossless: boolean
  /** Whether this codec uses hardware acceleration. */
  isHardware: boolean
}
/** A decoded frame returned by `JsDecoder.decode` or accepted by `JsEncoder.encode`. */
export interface JsDecodedFrame {
  /** Raw sample/pixel data. */
  payload: Buffer
  /** Presentation timestamp. */
  pts: number
  /** Decode timestamp. */
  dts: number
  /** Whether this is a sync point. */
  isKeyframe: boolean
  /** Duration in codec-defined units. */
  duration: number
}
/** An encoded packet returned by `JsEncoder.encode` or accepted by `JsDecoder.decode`. */
export interface JsEncodedPacket {
  /** Encoded bitstream. */
  payload: Buffer
  /** Presentation timestamp. */
  pts: number
  /** Decode timestamp. */
  dts: number
  /** Sync point. */
  isKeyframe: boolean
  /** Duration in codec-defined units. */
  duration: number
}
/** Build a decoder for the given codec name. */
export declare function createDecoder(name: string, config?: JsCodecConfig | undefined | null): JsDecoder
/** Build an encoder for the given codec name. */
export declare function createEncoder(name: string, config?: JsCodecConfig | undefined | null): JsEncoder
/** JavaScript handle to the global codec registry. */
export declare class JsCodecRegistry {
  /** Build a new handle. (All instances share the same global registry.) */
  constructor()
  /** Return the list of all registered codec names (sorted). */
  names(): Array<string>
  /**
   * Return descriptors filtered by media kind.
   * `kind` must be `"audio"`, `"video"`, `"subtitle"`, or `null`.
   */
  list(kind?: string | undefined | null): Array<JsCodecDescriptor>
  /** Find a codec by name. Returns `null` if not found. */
  find(name: string): JsCodecDescriptor | null
}
/** Stateful decoder. Build with [`createDecoder`]. */
export declare class JsDecoder {
  /** Codec name (e.g. `"pcm_s16le"`). */
  get name(): string
  /** Decode one packet and return the resulting frame. */
  decode(data: Buffer, pts?: number | undefined | null): Promise<JsDecodedFrame>
  /** Flush any buffered frames at end of stream. */
  flush(): Promise<Array<JsDecodedFrame>>
  /** Reset internal state (e.g. on seek). */
  reset(): Promise<void>
}
/** Stateful encoder. Build with [`createEncoder`]. */
export declare class JsEncoder {
  /** Codec name (e.g. `"pcm_s16le"`). */
  get name(): string
  /** Encode one decoded frame and return the resulting packet. */
  encode(frame: JsDecodedFrame): Promise<JsEncodedPacket>
  /** Flush any buffered packets. */
  flush(): Promise<Array<JsEncodedPacket>>
  /** Reset internal state. */
  reset(): Promise<void>
}
